'use client';

// Event and category data for EventMatch

export interface Event {
    objectID: string;
    title: string;
    description: string;
    category: string;
    date: string;
    time: string;
    location: string;
    city: string;
    price: number;
    image: string;
    attendees: number;
    maxAttendees: number;
    featured: boolean;
    tags: string[];
    organizer: string;
    rating: number;
}

export const categories = [
    { id: 'all', name: 'All Events', icon: '✨', color: '#667eea' },
    { id: 'music', name: 'Music', icon: '🎵', color: '#f093fb' },
    { id: 'sports', name: 'Sports', icon: '⚽', color: '#4facfe' },
    { id: 'art', name: 'Art & Culture', icon: '🎨', color: '#43e97b' },
    { id: 'tech', name: 'Tech', icon: '💻', color: '#fa709a' },
    { id: 'food', name: 'Food & Drink', icon: '🍕', color: '#f8b739' },
    { id: 'wellness', name: 'Wellness', icon: '🧘', color: '#a8edea' },
    { id: 'business', name: 'Business', icon: '💼', color: '#667eea' },
    { id: 'education', name: 'Education', icon: '📚', color: '#f093fb' },
];

export const sampleEvents: Event[] = [
    // MUSIC EVENTS
    {
        objectID: '1',
        title: 'Arijit Singh Live Concert',
        description: 'Experience the magic of Bollywood\'s most beloved voice in an unforgettable evening of soulful melodies and chart-topping hits.',
        category: 'music',
        date: '2026-02-15',
        time: '7:00 PM',
        location: 'MMRDA Grounds, BKC',
        city: 'Mumbai',
        price: 2500,
        image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
        attendees: 15000,
        maxAttendees: 20000,
        featured: true,
        tags: ['bollywood', 'live music', 'concert'],
        organizer: 'BookMyShow Live',
        rating: 4.9,
    },
    {
        objectID: '2',
        title: 'EDM Night: Sunburn Arena',
        description: 'Dance the night away with international DJs spinning the hottest electronic beats. Laser shows, pyrotechnics, and pure energy!',
        category: 'music',
        date: '2026-02-20',
        time: '9:00 PM',
        location: 'Mahalaxmi Race Course',
        city: 'Mumbai',
        price: 3500,
        image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800',
        attendees: 8000,
        maxAttendees: 12000,
        featured: true,
        tags: ['edm', 'party', 'nightlife'],
        organizer: 'Sunburn',
        rating: 4.7,
    },
    {
        objectID: '3',
        title: 'Classical Fusion: Ravi Shankar Tribute',
        description: 'A mesmerizing blend of Indian classical and Western orchestral music honoring the legendary sitar maestro.',
        category: 'music',
        date: '2026-02-25',
        time: '6:30 PM',
        location: 'NCPA Tata Theatre',
        city: 'Mumbai',
        price: 1500,
        image: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
        attendees: 800,
        maxAttendees: 1000,
        featured: false,
        tags: ['classical', 'fusion', 'cultural'],
        organizer: 'NCPA',
        rating: 4.8,
    },
    {
        objectID: '4',
        title: 'Jazz Under the Stars',
        description: 'Intimate rooftop jazz session featuring local artists. Wine, cheese, and smooth saxophone under the city lights.',
        category: 'music',
        date: '2026-03-01',
        time: '8:00 PM',
        location: 'The Quarter Rooftop',
        city: 'Mumbai',
        price: 1200,
        image: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
        attendees: 120,
        maxAttendees: 150,
        featured: false,
        tags: ['jazz', 'rooftop', 'intimate'],
        organizer: 'Mumbai Jazz Society',
        rating: 4.6,
    },
    {
        objectID: '5',
        title: 'Rock Revival: 90s Hits',
        description: 'Headbang to the greatest rock anthems of the 90s with tribute bands performing Nirvana, Pearl Jam, and more!',
        category: 'music',
        date: '2026-03-05',
        time: '7:30 PM',
        location: 'Hard Rock Cafe',
        city: 'Pune',
        price: 999,
        image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800',
        attendees: 300,
        maxAttendees: 400,
        featured: false,
        tags: ['rock', '90s', 'tribute'],
        organizer: 'Rock Nation',
        rating: 4.5,
    },

    // SPORTS EVENTS
    {
        objectID: '6',
        title: 'Mumbai Marathon 2026',
        description: 'Join India\'s largest marathon! Full marathon, half marathon, and dream run categories available for all fitness levels.',
        category: 'sports',
        date: '2026-01-19',
        time: '5:30 AM',
        location: 'CST to Marine Drive',
        city: 'Mumbai',
        price: 1500,
        image: 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800',
        attendees: 45000,
        maxAttendees: 55000,
        featured: true,
        tags: ['marathon', 'running', 'fitness'],
        organizer: 'Procam International',
        rating: 4.9,
    },
    {
        objectID: '7',
        title: 'IPL 2026: MI vs CSK',
        description: 'The ultimate rivalry! Watch Mumbai Indians take on Chennai Super Kings in this blockbuster IPL clash.',
        category: 'sports',
        date: '2026-04-10',
        time: '7:30 PM',
        location: 'Wankhede Stadium',
        city: 'Mumbai',
        price: 2000,
        image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
        attendees: 30000,
        maxAttendees: 33000,
        featured: true,
        tags: ['cricket', 'ipl', 't20'],
        organizer: 'BCCI',
        rating: 4.9,
    },
    {
        objectID: '8',
        title: 'Premier League Football Screening',
        description: 'Watch Manchester United vs Liverpool LIVE on the big screen with fellow fans. Free beer and nachos!',
        category: 'sports',
        date: '2026-03-14',
        time: '10:00 PM',
        location: 'Toit Brewpub',
        city: 'Bangalore',
        price: 500,
        image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800',
        attendees: 180,
        maxAttendees: 200,
        featured: false,
        tags: ['football', 'screening', 'epl'],
        organizer: 'Football Fanatics India',
        rating: 4.4,
    },
    {
        objectID: '9',
        title: 'Badminton Championship',
        description: 'State-level badminton tournament with cash prizes. Categories: Singles, Doubles, and Mixed Doubles.',
        category: 'sports',
        date: '2026-03-20',
        time: '9:00 AM',
        location: 'Shree Shiv Chhatrapati Sports Complex',
        city: 'Pune',
        price: 300,
        image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800',
        attendees: 200,
        maxAttendees: 256,
        featured: false,
        tags: ['badminton', 'tournament', 'competition'],
        organizer: 'Pune District Badminton Association',
        rating: 4.3,
    },
    {
        objectID: '10',
        title: 'Yoga at Sunrise: Beach Session',
        description: 'Start your day with energizing yoga on the beach. All levels welcome. Mats and refreshments provided.',
        category: 'sports',
        date: '2026-02-22',
        time: '6:00 AM',
        location: 'Juhu Beach',
        city: 'Mumbai',
        price: 0,
        image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
        attendees: 75,
        maxAttendees: 100,
        featured: false,
        tags: ['yoga', 'beach', 'wellness', 'free'],
        organizer: 'Art of Living',
        rating: 4.7,
    },

    // TECH EVENTS
    {
        objectID: '11',
        title: 'AI & ML Summit 2026',
        description: 'India\'s premier AI conference featuring talks from Google, Microsoft, and OpenAI leaders. Workshops and networking included.',
        category: 'tech',
        date: '2026-03-15',
        time: '9:00 AM',
        location: 'HICC Convention Center',
        city: 'Hyderabad',
        price: 5000,
        image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
        attendees: 2500,
        maxAttendees: 3000,
        featured: true,
        tags: ['ai', 'ml', 'conference', 'tech'],
        organizer: 'TechSparks',
        rating: 4.8,
    },
    {
        objectID: '12',
        title: 'Hackathon: Build for India',
        description: '48-hour hackathon to solve real problems in healthcare, education, and agriculture. ₹10 lakh in prizes!',
        category: 'tech',
        date: '2026-03-08',
        time: '10:00 AM',
        location: 'IIT Bombay',
        city: 'Mumbai',
        price: 0,
        image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800',
        attendees: 400,
        maxAttendees: 500,
        featured: true,
        tags: ['hackathon', 'coding', 'startup', 'free'],
        organizer: 'E-Cell IIT Bombay',
        rating: 4.9,
    },
    {
        objectID: '13',
        title: 'React India Conference',
        description: 'Learn from core React team members and industry experts. Deep dives into React 19, Server Components, and more.',
        category: 'tech',
        date: '2026-04-05',
        time: '9:30 AM',
        location: 'Leela Palace',
        city: 'Bangalore',
        price: 8000,
        image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800',
        attendees: 600,
        maxAttendees: 800,
        featured: false,
        tags: ['react', 'javascript', 'frontend', 'conference'],
        organizer: 'ReactConf India',
        rating: 4.7,
    },
    {
        objectID: '14',
        title: 'Startup Pitch Night',
        description: 'Watch 10 promising startups pitch to top VCs. Network with founders, investors, and tech enthusiasts.',
        category: 'tech',
        date: '2026-02-28',
        time: '6:00 PM',
        location: 'WeWork Galaxy',
        city: 'Bangalore',
        price: 500,
        image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
        attendees: 150,
        maxAttendees: 200,
        featured: false,
        tags: ['startup', 'pitch', 'networking', 'vc'],
        organizer: 'YourStory',
        rating: 4.5,
    },
    {
        objectID: '15',
        title: 'Cloud Native Workshop',
        description: 'Hands-on workshop on Kubernetes, Docker, and AWS. Build and deploy a microservices app in one day.',
        category: 'tech',
        date: '2026-03-22',
        time: '10:00 AM',
        location: 'Microsoft Reactor',
        city: 'Bangalore',
        price: 1500,
        image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
        attendees: 60,
        maxAttendees: 80,
        featured: false,
        tags: ['cloud', 'kubernetes', 'docker', 'workshop'],
        organizer: 'CNCF Bangalore',
        rating: 4.6,
    },

    // FOOD EVENTS
    {
        objectID: '16',
        title: 'Mumbai Street Food Festival',
        description: 'Celebrate the flavors of Mumbai! 50+ stalls featuring vada pav, pav bhaji, chaat, and more iconic dishes.',
        category: 'food',
        date: '2026-02-28',
        time: '4:00 PM',
        location: 'Bandra Kurla Complex',
        city: 'Mumbai',
        price: 200,
        image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
        attendees: 5000,
        maxAttendees: 8000,
        featured: true,
        tags: ['street food', 'festival', 'indian'],
        organizer: 'Mumbai Foodie Club',
        rating: 4.6,
    },
    {
        objectID: '17',
        title: 'Wine Tasting: Sula Vineyards',
        description: 'Sample 12 premium wines with expert sommeliers. Includes vineyard tour and gourmet cheese pairing.',
        category: 'food',
        date: '2026-03-10',
        time: '11:00 AM',
        location: 'Sula Vineyards',
        city: 'Nashik',
        price: 2500,
        image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
        attendees: 80,
        maxAttendees: 100,
        featured: false,
        tags: ['wine', 'tasting', 'vineyard', 'luxury'],
        organizer: 'Sula Wines',
        rating: 4.8,
    },
    {
        objectID: '18',
        title: 'Masterclass: Italian Pizza Making',
        description: 'Learn to make authentic Neapolitan pizza from an Italian chef. Take home your own dough and recipes!',
        category: 'food',
        date: '2026-03-05',
        time: '3:00 PM',
        location: 'Foodhall Cooking Studio',
        city: 'Mumbai',
        price: 3500,
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
        attendees: 15,
        maxAttendees: 20,
        featured: false,
        tags: ['cooking', 'italian', 'pizza', 'masterclass'],
        organizer: 'Foodhall',
        rating: 4.9,
    },
    {
        objectID: '19',
        title: 'Craft Beer Festival',
        description: '20+ microbreweries, live music, and food trucks. Sample the best craft beers from across India.',
        category: 'food',
        date: '2026-03-18',
        time: '5:00 PM',
        location: 'UB City',
        city: 'Bangalore',
        price: 800,
        image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800',
        attendees: 3000,
        maxAttendees: 4000,
        featured: true,
        tags: ['beer', 'craft', 'festival', 'nightlife'],
        organizer: 'Bangalore Brew Collective',
        rating: 4.5,
    },
    {
        objectID: '20',
        title: 'Biryani Trail Food Walk',
        description: 'Explore the legendary biryani joints of Old Delhi. 5 stops, unlimited samples, and rich history.',
        category: 'food',
        date: '2026-02-25',
        time: '12:00 PM',
        location: 'Jama Masjid',
        city: 'Delhi',
        price: 1200,
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
        attendees: 20,
        maxAttendees: 25,
        featured: false,
        tags: ['biryani', 'food walk', 'heritage', 'delhi'],
        organizer: 'Delhi Food Walks',
        rating: 4.7,
    },

    // ART & CULTURE EVENTS
    {
        objectID: '21',
        title: 'Art Exhibition: Contemporary India',
        description: 'Showcasing 50+ works from emerging Indian artists. Paintings, sculptures, and digital art installations.',
        category: 'art',
        date: '2026-03-01',
        time: '10:00 AM',
        location: 'Jehangir Art Gallery',
        city: 'Mumbai',
        price: 0,
        image: 'https://images.unsplash.com/photo-1531913764164-f85c52e6e654?w=800',
        attendees: 500,
        maxAttendees: 1000,
        featured: false,
        tags: ['art', 'exhibition', 'contemporary', 'free'],
        organizer: 'Jehangir Art Gallery',
        rating: 4.4,
    },
    {
        objectID: '22',
        title: 'Kathak Dance Performance',
        description: 'Witness the grace of Kathak by Padmashri Birju Maharaj\'s disciples. A 2-hour spectacle of classical dance.',
        category: 'art',
        date: '2026-03-12',
        time: '6:30 PM',
        location: 'Shanmukhananda Hall',
        city: 'Mumbai',
        price: 800,
        image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800',
        attendees: 600,
        maxAttendees: 800,
        featured: true,
        tags: ['dance', 'kathak', 'classical', 'cultural'],
        organizer: 'Sangeet Natak Akademi',
        rating: 4.8,
    },
    {
        objectID: '23',
        title: 'Photography Walk: Heritage Mumbai',
        description: 'Capture the colonial architecture of South Mumbai with a professional photographer guide.',
        category: 'art',
        date: '2026-02-23',
        time: '7:00 AM',
        location: 'Gateway of India',
        city: 'Mumbai',
        price: 600,
        image: 'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=800',
        attendees: 25,
        maxAttendees: 30,
        featured: false,
        tags: ['photography', 'heritage', 'walk', 'architecture'],
        organizer: 'Mumbai Photo Club',
        rating: 4.5,
    },
    {
        objectID: '24',
        title: 'Pottery Workshop',
        description: 'Learn the ancient art of pottery. Create your own bowls, vases, and decorative pieces on the wheel.',
        category: 'art',
        date: '2026-03-08',
        time: '2:00 PM',
        location: 'The Pottery Studio',
        city: 'Pune',
        price: 1500,
        image: 'https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=800',
        attendees: 12,
        maxAttendees: 15,
        featured: false,
        tags: ['pottery', 'workshop', 'crafts', 'creative'],
        organizer: 'Clay Tales',
        rating: 4.6,
    },
    {
        objectID: '25',
        title: 'Stand-up Comedy Night',
        description: 'Laugh out loud with India\'s top comedians including Zakir Khan, Biswa, and Kanan Gill.',
        category: 'art',
        date: '2026-03-25',
        time: '8:00 PM',
        location: 'Canvas Laugh Club',
        city: 'Mumbai',
        price: 1200,
        image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
        attendees: 280,
        maxAttendees: 300,
        featured: true,
        tags: ['comedy', 'standup', 'entertainment', 'nightlife'],
        organizer: 'Canvas Laugh Club',
        rating: 4.9,
    },

    // WELLNESS EVENTS
    {
        objectID: '26',
        title: 'Meditation Retreat: 3-Day Silent',
        description: 'Disconnect from the world and reconnect with yourself. Vipassana-style meditation in serene mountains.',
        category: 'wellness',
        date: '2026-03-28',
        time: '12:00 PM',
        location: 'Osho Meditation Resort',
        city: 'Pune',
        price: 8000,
        image: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800',
        attendees: 40,
        maxAttendees: 50,
        featured: true,
        tags: ['meditation', 'retreat', 'wellness', 'spiritual'],
        organizer: 'Osho International',
        rating: 4.9,
    },
    {
        objectID: '27',
        title: 'Mental Health Awareness Talk',
        description: 'Expert psychologists discuss anxiety, depression, and self-care strategies. Q&A session included.',
        category: 'wellness',
        date: '2026-02-26',
        time: '5:00 PM',
        location: 'Godrej Culture Lab',
        city: 'Mumbai',
        price: 0,
        image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800',
        attendees: 150,
        maxAttendees: 200,
        featured: false,
        tags: ['mental health', 'talk', 'wellness', 'free'],
        organizer: 'iCall Foundation',
        rating: 4.7,
    },
    {
        objectID: '28',
        title: 'Spa Day: Ayurvedic Wellness',
        description: 'Full-day Ayurvedic spa experience with massages, treatments, and healthy organic meals.',
        category: 'wellness',
        date: '2026-03-15',
        time: '9:00 AM',
        location: 'Ananda in the Himalayas',
        city: 'Rishikesh',
        price: 12000,
        image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
        attendees: 15,
        maxAttendees: 20,
        featured: true,
        tags: ['spa', 'ayurveda', 'luxury', 'wellness'],
        organizer: 'Ananda Spa',
        rating: 5.0,
    },

    // BUSINESS EVENTS
    {
        objectID: '29',
        title: 'Entrepreneur Summit 2026',
        description: 'Connect with 500+ entrepreneurs, investors, and mentors. Keynotes, panels, and power networking.',
        category: 'business',
        date: '2026-04-12',
        time: '9:00 AM',
        location: 'Taj Lands End',
        city: 'Mumbai',
        price: 7500,
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
        attendees: 400,
        maxAttendees: 500,
        featured: true,
        tags: ['business', 'entrepreneur', 'networking', 'summit'],
        organizer: 'TiE Mumbai',
        rating: 4.6,
    },
    {
        objectID: '30',
        title: 'Women in Leadership Forum',
        description: 'Inspiring talks by women leaders from Fortune 500 companies. Mentorship matching and breakout sessions.',
        category: 'business',
        date: '2026-03-08',
        time: '10:00 AM',
        location: 'The Lalit',
        city: 'Delhi',
        price: 3000,
        image: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800',
        attendees: 250,
        maxAttendees: 300,
        featured: true,
        tags: ['women', 'leadership', 'business', 'networking'],
        organizer: 'FICCI FLO',
        rating: 4.8,
    },

    // EDUCATION EVENTS
    {
        objectID: '31',
        title: 'Study Abroad Fair 2026',
        description: 'Meet representatives from 100+ universities in USA, UK, Canada, and Australia. Free counseling!',
        category: 'education',
        date: '2026-03-02',
        time: '10:00 AM',
        location: 'JW Marriott',
        city: 'Mumbai',
        price: 0,
        image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
        attendees: 2000,
        maxAttendees: 3000,
        featured: false,
        tags: ['education', 'study abroad', 'university', 'free'],
        organizer: 'IDP Education',
        rating: 4.3,
    },
    {
        objectID: '32',
        title: 'Data Science Bootcamp',
        description: '6-hour intensive bootcamp covering Python, Pandas, ML basics. Certificate and job placement assistance.',
        category: 'education',
        date: '2026-03-16',
        time: '9:00 AM',
        location: '91springboard',
        city: 'Bangalore',
        price: 2000,
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        attendees: 80,
        maxAttendees: 100,
        featured: false,
        tags: ['data science', 'bootcamp', 'python', 'education'],
        organizer: 'UpGrad',
        rating: 4.5,
    },
];

// Helper functions
export function getEventsByCategory(category: string): Event[] {
    if (category === 'all') return sampleEvents;
    return sampleEvents.filter(event => event.category === category);
}

export function searchEvents(query: string): Event[] {
    const lowerQuery = query.toLowerCase();
    return sampleEvents.filter(event =>
        event.title.toLowerCase().includes(lowerQuery) ||
        event.description.toLowerCase().includes(lowerQuery) ||
        event.category.toLowerCase().includes(lowerQuery) ||
        event.city.toLowerCase().includes(lowerQuery) ||
        event.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
    );
}

export function getFeaturedEvents(): Event[] {
    return sampleEvents.filter(event => event.featured);
}

export function getFreeEvents(): Event[] {
    return sampleEvents.filter(event => event.price === 0);
}

export function getEventsByCity(city: string): Event[] {
    return sampleEvents.filter(event =>
        event.city.toLowerCase() === city.toLowerCase()
    );
}

export function getUpcomingEvents(limit: number = 10): Event[] {
    const today = new Date().toISOString().split('T')[0];
    return sampleEvents
        .filter(event => event.date >= today)
        .sort((a, b) => a.date.localeCompare(b.date))
        .slice(0, limit);
}
